//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Cspos.Persistance.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySale
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
