//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Cspos.Persistance.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Kits = new HashSet<Kit>();
            this.SupplierLists = new HashSet<SupplierList>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string Description { get; set; }
        public Nullable<bool> FoodStampable { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<System.DateTime> LastReceived { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Reference { get; set; }
        public Nullable<double> Weight { get; set; }
        public bool Weighed { get; set; }
        public Nullable<int> PrefferredSupplierID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> Discountable { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<System.DateTime> SaleStartDate { get; set; }
        public Nullable<System.DateTime> SaleEndDate { get; set; }
        public bool OnSale { get; set; }
        public Nullable<int> TaxID { get; set; }
        public bool Taxable { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Kit> Kits { get; set; }
        public virtual ICollection<SupplierList> SupplierLists { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
