//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Cspos.Persistance.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitEntry
    {
        public int ID { get; set; }
        public Nullable<int> KitID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual Kit Kit { get; set; }
    }
}
